### ISSUE TITLE
jDOSBox 3.3

### ISSUE THREAD

**Issue by Torinde** [Tennessene/jDOSBox#11]
You mention this project is based on r808 (version 3?) while [there are also versions up to 3.3](https://sourceforge.net/projects/jsdosbox/files/version3/):
```
jsdosbox3.3.zip	2016-01-10	497.4 kB
jsdosbox3.2.zip	2015-02-14	432.2 kB
jsdosbox3.1.zip	2015-01-19	421.8 kB
jsdosbox3.zip	2014-09-11	428.2 kB
```

**Comment by Torinde** [comment]
Also relevant:
[EM-DOSBox / DOSBox ported to Emscripten](https://github.com/dreamlayers/em-dosbox) - heavily used by Internet Archive
[js-dos](https://github.com/caiiiycuk/js-dos)
[DOSee](https://github.com/bengarrett/DOSee)
[Rewarp](https://rewarp.app/) ([GitHub](https://github.com/tomas/em-dosbox))

**Comment by Torinde** [comment]
Have you thought instead of making a web/Emscripten build of DOSBox-X (joncampbell123/dosbox-x/issues/882)? Maybe starting from [DOSBox-X Emscripten](https://github.com/yksoft1/dosbox-x-vanilla-sdl/tree/emscripten).

**Comment by Tennessene** [comment]
I think you're getting this project confused. This project is strictly for a Java version and not for a JavaScript version. The reason is because the emulator is getting integrated into a plugin for server software that uses Java plugins. Thank you for trying to help though.

You must be thinking I'm still trying to integrate DOSBox into the web browser, but that is not what I'm trying to do 🙂
